In [25]:
# -*- coding: utf-8 -*-
# UTF-8 encoding when using korean
import numpy as np
user_input = int(input())

In [28]:
arr = [[1]*user_input]*user_input
arr = np.array(arr)
base = arr[0].copy()
for i in range(1, int(user_input/2)+1):
	if i%2 == 1:
		base[i:-i] = [0]
		arr[i] = base
		arr[-i-1] = base
		base = arr[i].copy()
	else:
		base[i:-i] = [1]
		arr[i] = base
		arr[-i-1] = base
		base = arr[i].copy()
	
	if arr[i][i-1] == 0:
		arr[i][i-1] = 1
	else:
		arr[i][i-1] = 0
	
	
for i in range(user_input):
	result = ''
	for j in arr[i]:
		if j == 1:
			result += '# '
		else:
			result += '  '

	print(result)

1
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 1 1 1 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
2
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 1 1 1 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
3
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 1 1 1 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [18]:
2%2

0